name: "Issue Notification Action"
description: "Post notifications to Slack or Discord when GitHub issues meet certain criteria"
author: "Your Name"
inputs:
  # Webhook configuration
  slack_webhook_url:
    description: "Slack webhook URL for posting messages"
    required: false
  discord_webhook_url:
    description: "Discord webhook URL for posting messages"
    required: false

  # Issue filters
  title_keywords:
    description: "Comma-separated keywords to filter issues by title"
    required: false
    default: ""
  required_labels:
    description: "Comma-separated labels that must be present on the issue"
    required: false
    default: ""
  excluded_labels:
    description: "Comma-separated labels that should exclude the issue"
    required: false
    default: ""

  # Thresholds
  reaction_threshold:
    description: "Minimum number of reactions required to trigger notification"
    required: false
    default: "5"
  comment_threshold:
    description: "Minimum number of comments required to trigger notification"
    required: false
    default: "3"

  # Message customization
  message_template:
    description: "Custom message template. Use {title}, {url}, {author}, {reactions}, {comments}, {repo}, {repo_url}, {repo_link}, {created_minutes_ago}, {created_hours_ago}, {created_days_ago}, {created_at}, {created_ago} as placeholders"
    required: false
    default: '**{title}**\nBy: {author}\nReactions: {reactions} | Comments: {comments}\nRepository: {repo_link}\nCreated: {created_hours_ago} hours ago\n{url}'
  new_issue_prefix:
    description: "Prefix for new issue notifications (use {repo_link} for repository link)"
    required: false
    default: "🚨 New issue created on {repo_link}!"
  threshold_prefix:
    description: "Prefix for threshold notifications (use {repo_link} for repository link)"
    required: false
    default: "📈 High-engagement issue detected on {repo_link}!"

  # Notification settings
  notify_on_create:
    description: "Send notification when new issue is created (if it matches filters)"
    required: false
    default: "true"
  notify_on_threshold:
    description: "Send notification when issue reaches reaction/comment thresholds"
    required: false
    default: "true"

  # Batch checking configuration
  check_all_open_issues:
    description: "Check all open issues for thresholds when action runs (useful for catching reactions)"
    required: false
    default: "false"
  max_issues_to_check:
    description: "Maximum number of issues to check during batch processing"
    required: false
    default: "100"
  issue_state:
    description: "Which issues to check during batch processing (open, closed, all)"
    required: false
    default: "open"

runs:
  using: "node20"
  main: "dist/index.js"

branding:
  icon: "bell"
  color: "blue"
