name: 🐛 Bug report
description: Report a bug with the GitHub Action
title: "[BUG] "
labels: ["bug"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: dropdown
    id: issue_type
    attributes:
      label: Type of Issue
      description: Select the category that best describes the issue.
      options:
        - Action not triggering
        - Notification not sent
        - Filter not working
        - Configuration error
        - Other Bug
    validations:
      required: true

  - type: textarea
    id: describe_bug
    attributes:
      label: Describe the Bug
      description: A clear and concise description of what the bug is.
      placeholder: |
        **Environment:**
        - GitHub Action version:
        - Repository type (public/private):
        - Webhook platform (Slack/Discord):
        - GitHub event that triggered the action:

        **Issue details (if applicable):**
        - Issue title:
        - Issue labels:
        - Number of reactions:
        - Number of comments:
    validations:
      required: true

  - type: textarea
    id: workflow_config
    attributes:
      label: Workflow Configuration
      description: Please share your workflow configuration (with sensitive information redacted).
      placeholder: |
        ```yaml
        name: Issue Notifications
        on:
          issues:
            types: [opened, edited]
          issue_comment:
            types: [created]

        jobs:
          notify:
            runs-on: ubuntu-latest
            steps:
              - name: Issue Notification Action
                uses: your-username/github-action-issue-ack@v1
                with:
                  slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
                  title_keywords: "urgent,security"
                  reaction_threshold: "5"
                  comment_threshold: "3"
        ```

  - type: textarea
    id: action_logs
    attributes:
      label: Action Logs
      description: Add the GitHub Actions logs that show the error or unexpected behavior.
      placeholder: |
        Action logs here (from the "Issue Notification Action" step)

  - type: textarea
    id: reproduction_steps
    attributes:
      label: Steps to Reproduce
      description: Please provide steps to reproduce the issue.
      placeholder: |
        1. Set up the action with the following configuration...
        2. Create an issue with the following criteria...
        3. Expected: Notification should be sent to Slack/Discord
        4. Actual: [What actually happened]

  - type: checkboxes
    id: preflight
    attributes:
      label: Preliminary Checks
      description: Please confirm you've completed the following before filing the issue.
      options:
        - label: I have updated to the latest version of the action
        - label: I have read the README documentation
        - label: I have checked the webhook setup guide
        - label: I have searched for existing GitHub issues
        - label: I have tested my webhook URLs manually
