name: Release and Publish

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build action
        run: npm run build

      - name: Create Release
        id: release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            ## What's Changed

            This release includes the latest updates to the GitHub Action for issue notifications.

            ### Features
            - Automatic issue notification to Slack/Discord
            - Configurable filters and thresholds
            - Support for both new issues and high-engagement issues
            - Smart time formatting with `{created_ago}` variable

            ### Usage
            ```yaml
            - uses: ${{ github.repository }}@${{ github.ref_name }}
            ```

            For detailed configuration options, see the [README](https://github.com/${{ github.repository }}#readme).
          draft: false
          prerelease: false
          files: dist/index.js
